# Database connection
spring.datasource.url=jdbc:postgresql://localhost:5455/carbon_exchange
spring.datasource.username=${LOCAL_DB_USER:admin}
spring.datasource.password=${LOCAL_DB_PASSWORD:password}

# Hibernate settings (Create tables automatically for dev, do not use in prod)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect